project:
  type: website
website:
  title: "MyBook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true

editor: source

